- hosts: all
  tasks:  
    - name: Download mina binary
      shell: 
        cmd: |
          echo "deb [trusted=yes] http://packages.o1test.net stretch stable" | sudo tee /etc/apt/sources.list.d/mina.list
          sudo apt-get update
          sudo apt-get install -y curl unzip mina-mainnet=1.2.2-feee67c
    
    - name: Check that mina was installed correctly
      shell:
        cmd: mina version
      register: mina_version

    - name: Print our the mina version
      debug:
        var: mina_version

    - name: Install mina-generate-keypair
      shell:
        cmd: |
          echo "deb [trusted=yes] http://packages.o1test.net stretch stable" | sudo tee /etc/apt/sources.list.d/mina.list
          sudo apt-get update
          sudo apt-get install mina-generate-keypair=1.2.2-feee67c

    - name: Create the Keys directory for the key-pair
      shell:
        cmd: |
          mkdir ~/keys
          chmod 700 ~/keys

    - name: Generate key pair
      shell:
        cmd: |
          mina-generate-keypair --privkey-path ~/keys/my-wallet
          chmod 600 ~/keys/my-wallet
      environment: 
        CODA_PRIVKEY_PASS: gopher

    - name: Install mina mainnet
      shell:
        cmd: |
          echo "deb [trusted=yes] http://packages.o1test.net stretch stable" | sudo tee /etc/apt/sources.list.d/mina.list
          sudo apt-get update
          sudo apt-get install -y curl unzip mina-mainnet=1.2.2-feee67c
                
    - name: Copy the .mina-env file to the server
      copy:
        src: config/.mina-env
        dest: /home/ubuntu

    - name: Startup mina services
      shell:
        cmd: |
          systemctl --user daemon-reload
          systemctl --user start mina
          systemctl --user enable mina
          sudo loginctl enable-linger
    
    - name: Check mina status
      shell: systemctl --user status mina
      register: mina_status

    - name: Debug mina status
      debug:
        var: mina_status